"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Info, RefreshCw, Search, X } from "lucide-react";
import { formatDuration } from "./PlatformAnalyticsSection";
import type { CustomerActivityItem, CustomerActivityResponse, CustomerAttentionItem, CustomerAttentionResponse, CustomerSummary } from "../types";

const TOOLTIPS = {
  attention: "A support-priority score based on unresolved conversations, waiting time, negative customer messages, repeat contacts, and conversation priority.",
  repeat: "The customer opened another conversation within seven days. This does not necessarily mean the same issue occurred again.",
  waiting: "The latest sent message in an open or pending conversation came from the customer.",
  open: "Conversations currently marked open or pending. This is a current snapshot.",
};
const levelStyle = { normal: "bg-surface-wash text-foreground", watch: "bg-blue-50 text-blue-700", needs_attention: "bg-[var(--warning-surface)] text-[var(--warning)]", urgent_attention: "bg-[var(--error-surface)] text-[var(--error-foreground)]" };
const levelLabel = { normal: "Normal", watch: "Watch", needs_attention: "Needs Attention", urgent_attention: "Urgent Attention" };
const date = (value: string | null) => value ? new Date(value).toLocaleString() : "Not Available Yet";

function Tip({ label, text }: { label: string; text: string }) { return <span title={text}>{label} <Info aria-label={text} size={12} className="inline cursor-help" /></span>; }

export default function CustomerAnalyticsSection({ summary, active, attention, onRefresh, refreshing }: { summary: CustomerSummary; active: CustomerActivityResponse; attention: CustomerAttentionResponse; onRefresh: () => void; refreshing: boolean }) {
  const [tab, setTab] = useState<"active" | "attention">("active");
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(0);
  const [sortBy, setSortBy] = useState("activity");
  const [selected, setSelected] = useState<CustomerAttentionItem | null>(null);
  const activeRows = useMemo(() => active.customers.filter((item) => item.display_name.toLowerCase().includes(search.toLowerCase())).sort((a,b) => sortBy === "conversations" ? b.total_conversations-a.total_conversations : sortBy === "last_contact" ? String(b.last_contact_at).localeCompare(String(a.last_contact_at)) : b.total_messages-a.total_messages), [active.customers, search, sortBy]);
  const attentionRows = useMemo(() => attention.customers.filter((item) => item.display_name.toLowerCase().includes(search.toLowerCase())).sort((a,b) => sortBy === "waiting" ? (b.longest_waiting_seconds||0)-(a.longest_waiting_seconds||0) : sortBy === "open" ? b.unresolved_conversation_count-a.unresolved_conversation_count : b.attention_score-a.attention_score), [attention.customers, search, sortBy]);
  const rows = tab === "active" ? activeRows : attentionRows;
  const pageRows = rows.slice(page * 10, page * 10 + 10);
  const cards = [
    ["Active Customers", summary.metrics.active_customers.value], ["New Customers", summary.metrics.new_customers.value],
    ["Returning Customers", summary.metrics.returning_customers.value], ["Waiting for Reply", summary.metrics.customers_waiting_for_reply.value],
    ["Customers Needing Attention", summary.metrics.customers_needing_attention.value], ["Urgent Attention", summary.metrics.customers_with_urgent_attention.value],
    ["Repeat-Contact Customers", summary.metrics.repeat_contact_customers.value],
  ];
  return <section className="space-y-6 rounded-[2rem] bg-background p-4 text-foreground sm:p-6" aria-labelledby="customer-activity-title">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 id="customer-activity-title" className="text-2xl font-black">Customer Activity</h2><p className="mt-1 text-sm text-muted-foreground">See who contacts support most and which customers may need review first.</p></div><button type="button" onClick={onRefresh} className="ds-button ds-button-secondary"><RefreshCw size={14} className={refreshing ? "animate-spin" : ""} /> Refresh Customers</button></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(([label,value]) => <article key={String(label)} className="rounded-2xl border border-border bg-surface p-4"><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{value?.toLocaleString() ?? 0}</p></article>)}</div>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-xl bg-surface-wash p-1"><button onClick={() => { setTab("active"); setPage(0); setSortBy("activity"); }} className={`rounded-lg px-4 py-2 text-xs font-bold ${tab === "active" ? "bg-surface shadow-sm" : "text-muted-foreground"}`}>Most Active Customers</button><button onClick={() => { setTab("attention"); setPage(0); setSortBy("activity"); }} className={`rounded-lg px-4 py-2 text-xs font-bold ${tab === "attention" ? "bg-surface shadow-sm" : "text-muted-foreground"}`}>Customers Needing Attention</button></div><div className="flex gap-2"><select aria-label="Sort customers" value={sortBy} onChange={(event) => { setSortBy(event.target.value); setPage(0); }} className="rounded-xl border border-border bg-surface px-3 text-xs"><option value="activity">{tab === "active" ? "Most messages" : "Highest attention score"}</option><option value={tab === "active" ? "conversations" : "waiting"}>{tab === "active" ? "Most conversations" : "Longest wait"}</option><option value={tab === "active" ? "last_contact" : "open"}>{tab === "active" ? "Latest contact" : "Most open conversations"}</option></select><label className="flex items-center gap-2 rounded-xl border border-border bg-surface px-3"><Search size={14} /><input aria-label="Search customers" value={search} onChange={(event) => { setSearch(event.target.value); setPage(0); }} placeholder="Search customers" className="h-10 bg-transparent text-sm outline-none" /></label></div></div>
    {tab === "active" ? <ActiveTable rows={pageRows as CustomerActivityItem[]} /> : <AttentionTable rows={pageRows as CustomerAttentionItem[]} onSelect={setSelected} />}
    <div className="flex items-center justify-between"><p className="text-xs text-muted-foreground">Showing {rows.length ? page * 10 + 1 : 0}–{Math.min((page + 1) * 10, rows.length)} of {rows.length} matching customers.</p><div className="flex gap-2"><button className="ds-button ds-button-secondary" disabled={page === 0} onClick={() => setPage((value) => value - 1)}>Previous</button><button className="ds-button ds-button-secondary" disabled={(page + 1) * 10 >= rows.length} onClick={() => setPage((value) => value + 1)}>Next</button></div></div>
    <div className="flex gap-3 rounded-2xl border border-accent/20 bg-accent/10 p-4 text-xs text-foreground"><Info size={16} className="shrink-0 text-accent" /><div><p><Tip label="Waiting for Reply" text={TOOLTIPS.waiting} /></p><p className="mt-1"><Tip label="Repeat Contact" text={TOOLTIPS.repeat} /></p></div></div>
    {selected && <AttentionDrawer item={selected} onClose={() => setSelected(null)} />}
  </section>;
}

function ActiveTable({ rows }: { rows: CustomerActivityItem[] }) {
  return <div className="overflow-x-auto rounded-2xl border border-border bg-surface"><table className="min-w-[1050px] w-full text-left text-xs"><thead className="bg-surface-wash"><tr>{["Customer","Channels","Conversations","Customer Messages","Business Replies","Active Days","Currently Open","Negative Messages","Last Contact","Action"].map((label) => <th key={label} className="px-4 py-3">{label === "Currently Open" ? <Tip label={label} text={TOOLTIPS.open} /> : label}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.customer_id} className="border-t border-border"><td className="px-4 py-3 font-bold">{item.display_name}</td><td className="px-4 py-3 capitalize">{item.platforms_used.join(", ")}</td><td className="px-4 py-3">{item.total_conversations}</td><td className="px-4 py-3">{item.customer_messages}</td><td className="px-4 py-3">{item.business_replies}</td><td className="px-4 py-3">{item.active_days}</td><td className="px-4 py-3">{item.currently_open_conversations}</td><td className="px-4 py-3">{item.negative_customer_messages}</td><td className="px-4 py-3">{date(item.last_contact_at)}</td><td className="px-4 py-3"><Link href="/inbox" className="font-bold text-accent">Open inbox</Link></td></tr>)}</tbody></table>{rows.length === 0 && <p className="p-8 text-center text-sm text-muted-foreground">No active customers match this view.</p>}</div>;
}

function AttentionTable({ rows, onSelect }: { rows: CustomerAttentionItem[]; onSelect: (item: CustomerAttentionItem) => void }) {
  return <div className="overflow-x-auto rounded-2xl border border-border bg-surface"><table className="min-w-[1150px] w-full text-left text-xs"><thead className="bg-surface-wash"><tr>{["Customer","Attention Score","Attention Level","Main Reasons","Currently Open","Waiting for Reply","Longest Wait","Negative Messages","Repeat Contacts","Last Contact"].map((label) => <th key={label} className="px-4 py-3">{label === "Attention Score" ? <Tip label={label} text={TOOLTIPS.attention} /> : label}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.customer_id} onClick={() => onSelect(item)} className="cursor-pointer border-t border-border hover:bg-background"><td className="px-4 py-3 font-bold">{item.display_name}</td><td className="px-4 py-3 font-black">{item.attention_score}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 font-bold ${levelStyle[item.attention_level]}`}>{levelLabel[item.attention_level]}</span></td><td className="max-w-72 px-4 py-3">{item.primary_reasons.slice(0,2).join("; ")}</td><td className="px-4 py-3">{item.unresolved_conversation_count}</td><td className="px-4 py-3">{item.waiting_conversation_count}</td><td className="px-4 py-3">{formatDuration(item.longest_waiting_seconds)}</td><td className="px-4 py-3">{item.negative_customer_message_count}</td><td className="px-4 py-3">{item.repeat_contact_count}</td><td className="px-4 py-3">{date(item.last_contact_at)}</td></tr>)}</tbody></table>{rows.length === 0 && <p className="p-8 text-center text-sm text-muted-foreground">No customers currently meet the attention threshold.</p>}</div>;
}

function AttentionDrawer({ item, onClose }: { item: CustomerAttentionItem; onClose: () => void }) {
  return <div role="dialog" aria-label="Customer attention details" className="fixed inset-0 z-50 flex justify-end bg-slate-950/30"><div className="h-full w-full max-w-lg overflow-y-auto bg-surface p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold text-muted-foreground">Customers Needing Attention</p><h3 className="text-2xl font-black">{item.display_name}</h3></div><button aria-label="Close details" onClick={onClose}><X /></button></div><div className="mt-6 rounded-2xl bg-background p-5"><p className="text-xs text-muted-foreground">Attention Score</p><p className="text-4xl font-black">{item.attention_score}</p><span className={`mt-2 inline-flex rounded-full px-2 py-1 text-xs font-bold ${levelStyle[item.attention_level]}`}>{levelLabel[item.attention_level]}</span></div><div className="mt-6 space-y-3"><h4 className="font-black">Why this customer appears here</h4>{item.component_breakdown.map((component) => <div key={component.key} className="rounded-xl border border-border p-3"><div className="flex justify-between"><p className="font-bold">{component.label}</p><p className="font-black">+{component.contribution}</p></div><div className="my-2 h-2 rounded-full bg-surface-wash"><div className="h-2 rounded-full bg-accent" style={{ width: `${component.normalized_value * 100}%` }} /></div><p className="text-xs text-muted-foreground">{component.explanation}</p></div>)}</div><dl className="mt-6 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-muted-foreground">Currently Open</dt><dd className="font-bold">{item.unresolved_conversation_count}</dd></div><div><dt className="text-muted-foreground">Waiting for Reply</dt><dd className="font-bold">{item.waiting_conversation_count}</dd></div><div><dt className="text-muted-foreground">Longest Wait</dt><dd className="font-bold">{formatDuration(item.longest_waiting_seconds)}</dd></div><div><dt className="text-muted-foreground">Repeat Contacts</dt><dd className="font-bold">{item.repeat_contact_count}</dd></div></dl><Link href="/inbox" className="ds-button ds-button-primary mt-6 inline-flex">Open related conversations</Link></div></div>;
}
